---
- assert:
    that:
      - service_id | default('') | length > 0
      - item | default('') | length > 0 # volume_name according to docker-compose file

- name: Get infos on volume
  community.docker.docker_volume_info:
    name: "{{ service_id }}_{{ item }}"
  register: volume_info

- name: Add volume info to list
  set_fact:
    volume_info_list: "{{ volume_info_list | default([]) + [ volume_info ] }}"