---
# This is an example playbook to execute Ansible tests.
- name: Prepare Control host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: pip freeze
      command: pip freeze
      register: pip_freeze_cmd

    - debug:
        var: pip_freeze_cmd

    - name: Install pip packages
      ansible.builtin.pip:
        name:
          - requests-credssp==1.3.1

- name: Verify
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Include vars file
      include_vars:
        file: ./vars/main.yml

    - name: Run Linux verify
      when: ansible_os_family != "Windows"
      ansible.builtin.include_tasks: verify-linux.yml

    - name: Run Windows verify
      when: ansible_os_family == "Windows"
      ansible.builtin.include_tasks: verify-windows.yml
