---
namespace: fabos

name: docker_tcp

version: 1.0.0

readme: README.md

authors:
- Benjamin Goetz - Fraunhofer IPA

description: The collection provides playbooks for installing and uninstalling of docker on a target host (see "setup" role) and deploying and undeploying of container based on docker-compose files (see "use" role). The additional "inventory_helper" role helps to create an inventory in the context of the FabOS Service Lifecycle Management (SLM).

license:
- MIT

license_file: 'LICENSE'

tags: [docker, docker-compose, install, uninstall, deploy, undeploy]

dependencies: {}

repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker

build_ignore: []

