---
roles:
  - src: "git+https://github.com/FabOS-AI/molecule_vsphere.git"
    scm: git
    version: main
    name: molecule_vsphere

  - src: "git+https://github.com/FabOS-AI/fabos-slm-inventory-helper.git"
    scm: git
    version: main
    name: inventory_helper