---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: centos7
    template_name: centos-7
    groups: ['ssh']
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    converge: ../default-install/converge.yml
    verify: ../default-install/verify.yml
  inventory:
    group_vars:
      ssh:
        expose_docker_tcp_port: true
verifier:
  name: ansible
