---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: ubuntu1804
    template_name: ubuntu-18-04
    groups: ['ssh']

  - name: ubuntu2004
    template_name: ubuntu-20-04
    groups: ['ssh']

  - name: ubuntu2204
    template_name: ubuntu-22-04
    groups: ['ssh']
provisioner:
  name: ansible
  playbooks:
    create: ../../../setup/molecule/default/create.yml
    prepare: ../../../setup/molecule/default-install/converge.yml
    destroy: ../../../setup/molecule/default/destroy.yml
    converge: ../default-deploy/converge.yml
    verify: ../default-deploy/verify.yml
  inventory:
    group_vars:
      ssh:
        expose_docker_tcp_port: true
verifier:
  name: ansible
