---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: centos7
    template_name: centos-7
    groups: ['ssh']

  - name: centos8
    template_name: centos-stream-8
    groups: ['ssh']
provisioner:
  name: ansible
  playbooks:
    create: ../../../setup/molecule/default/create.yml
    prepare: ../default-undeploy/prepare.yml
    destroy: ../../../setup/molecule/default/destroy.yml
    converge: ../default-undeploy/converge.yml
    verify: ../default-undeploy/verify.yml
  inventory:
    group_vars:
      ssh:
        expose_docker_tcp_port: true
verifier:
  name: ansible
