---
- name: Install on CentOS
  when: ansible_distribution == 'CentOS'
  block:
    - name: Install the yum-utils package
      ansible.builtin.yum:
        name: yum-utils

    - name: Add stable docker repository
      ansible.builtin.yum_repository:
        name: docker
        description: Docker stable repository
        baseurl: "https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/x86_64/stable"
        gpgcheck: no

    - name: Install docker
      ansible.builtin.yum:
        name:
          - docker-ce-cli
        update_cache: yes

- name: Install on Ubuntu
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  block:
    - name: Add Docker’s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      register: apt_key_result
      until: not apt_key_result.failed
      retries: 20

    - name: Set up the stable repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present

    - name: Install docker engine
      ansible.builtin.apt:
        pkg:
          - docker-ce-cli
        update_cache: yes
      register: apt_result
      until: apt_result.rc is not defined
      retries: 20
      delay: 10

- name: Install 'docker', 'docker-compose' pip package
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose